# TOP Include – Global Declarations

## Purpose
Contains all global data declarations used across screens and includes.

TABLES: ZVIM_HDR .
TABLES: ZVIM_ITM .

TYPES: BEGIN OF LTY_ITEMS.
  INCLUDE STRUCTURE ZVIM_ITM.
  TYPES: SEL,
  END OF LTY_ITEMS.

DATA: LT_HEADER TYPE TABLE OF ZVIM_HDR,
      LWA_HEADER TYPE ZVIM_HDR.

DATA: LT_ITEMS TYPE TABLE OF LTY_ITEMS,
      LWA_ITEMS TYPE LTY_ITEMS.

DATA: POSTED(1) TYPE C.
DATA: LV_DISPLAY(1) TYPE C.
DATA: LV_GRID(1) TYPE C.
DATA: lv_generated_id TYPE NUMC10.
DATA: LV_SUMOFITEMS TYPE I.
DATA: LV_ITEMNO TYPE NUMC3 VALUE 1.
DATA: LV_SAKNR TYPE SAKNR,
              LV_KOSTL TYPE KOSTL.


DATA: LV_INVNO TYPE ZINUM.
DATA: LV_LIFNR TYPE LIFNR.
DATA: LV_BUKRS TYPE BUKRS.
DATA: LV_BLDAT TYPE BLDAT.


SELECTION-SCREEN: BEGIN OF SCREEN 301 AS SUBSCREEN.
  SELECT-OPTIONS S_INVNO FOR LV_INVNO.
  SELECT-OPTIONS S_LIFNR FOR LV_LIFNR.
  SELECT-OPTIONS S_BUKRS FOR LV_BUKRS.
  SELECT-OPTIONS S_BLDAT FOR LV_BLDAT.
SELECTION-SCREEN: END OF SCREEN 301.



INCLUDE zvim_user_command_0100i01.

INCLUDE zvim_status_0100o01.

INCLUDE zvim_user_command_0200i01.

INCLUDE zvim_status_0200o01.

INCLUDE zvim_status_0300o01.

INCLUDE zvim_user_command_0300i01.

INCLUDE zvim_vendor_listi01.

INCLUDE zvim_cc_listi01.

INCLUDE zvim_validate_costcenteri01.
